services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    networks:
      - loadbalancer-net
    environment:
      - BACKEND_SERVER1=server1
      - BACKEND_SERVER2=server2
      - BACKEND_SERVER3=server3
    depends_on:
      - server1
      - server2
      - server3

  server1:
    image: nginx
    container_name: server1
    networks:
      - loadbalancer-net
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  server2:
    image: nginx
    container_name: server2
    networks:
      - loadbalancer-net
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  server3:
    image: nginx
    container_name: server3
    networks:
      - loadbalancer-net
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loadbalancer-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - loadbalancer-net
    depends_on:
      - prometheus

networks:
  loadbalancer-net:
    driver: bridge
